
# Comment out the Extension that you do not want to use
services:
  processing-microservice-netlogo:
    build: 
      context: ./
      dockerfile: ./NetLogo/Dockerfile
    networks:
      - proxy
      - websocket-simulation

  #processing-microservice-mesa:
  #  build: ./Mesa/
  #  networks:
  #    - proxy
  #    - websocket-simulation
  

networks:
  proxy:
    external: true
  websocket-simulation:
    external: true
